name: Build Windows EXE

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.17

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Dependencies
        run: yarn install
        env:
          GYP_MSVS_VERSION: 2022

      - name: Build Project
        run: yarn build

      - name: Package Windows EXE
        run: yarn --cwd ./electron-app package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GYP_MSVS_VERSION: 2022

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RudironIDE-Windows-EXE
          path: electron-app/dist/*.exe
